import {
  readFile,
  readdir,
  rm
} from "node:fs/promises";
import path from "node:path";

type RecoveryPointDeletionManifest = {
  formatVersion: 1;
  auctionSession: {
    id: string;
  };
  database: {
    fileName: string;
  };
};

export type DeleteRecoveryPointInput = {
  auctionSessionId: string;
  fileName: string;
};

export type DeleteRecoveryPointResult = {
  fileName: string;
};

export class RecoveryPointNotFoundError
  extends Error {
  constructor() {
    super("Recovery point not found");
    this.name =
      "RecoveryPointNotFoundError";
  }
}

export type RecoveryPointDeletionServiceOptions = {
  backupRoot: string;
};

function isRecord(
  value: unknown
): value is Record<string, unknown> {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value)
  );
}

function isDeletionManifest(
  value: unknown
): value is RecoveryPointDeletionManifest {
  if (!isRecord(value)) {
    return false;
  }

  const auctionSession =
    value.auctionSession;
  const database =
    value.database;

  return (
    value.formatVersion === 1 &&
    isRecord(auctionSession) &&
    typeof auctionSession.id ===
      "string" &&
    isRecord(database) &&
    typeof database.fileName ===
      "string"
  );
}

async function findManifestPaths(
  directory: string
): Promise<string[]> {
  let entries;

  try {
    entries = await readdir(
      directory,
      {
        withFileTypes: true
      }
    );
  } catch (error) {
    if (
      error instanceof Error &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return [];
    }

    throw error;
  }

  const manifestPaths: string[] = [];

  for (const entry of entries) {
    const entryPath =
      path.join(
        directory,
        entry.name
      );

    if (entry.isDirectory()) {
      manifestPaths.push(
        ...await findManifestPaths(
          entryPath
        )
      );

      continue;
    }

    if (
      entry.isFile() &&
      entry.name.endsWith(".json")
    ) {
      manifestPaths.push(entryPath);
    }
  }

  return manifestPaths;
}

export class RecoveryPointDeletionService {
  private readonly backupRoot: string;

  constructor(
    options:
      RecoveryPointDeletionServiceOptions
  ) {
    this.backupRoot =
      options.backupRoot;
  }

  async deleteRecoveryPoint(
    input: DeleteRecoveryPointInput
  ): Promise<DeleteRecoveryPointResult> {
    /*
     * A recovery point identifier is always a
     * basename generated by the server.
     *
     * Reject path-like input before touching
     * the filesystem.
     */
    if (
      input.fileName.length === 0 ||
      path.basename(input.fileName) !==
        input.fileName ||
      !input.fileName.endsWith(
        ".sqlite"
      )
    ) {
      throw new RecoveryPointNotFoundError();
    }

    const manifestPaths =
      await findManifestPaths(
        this.backupRoot
      );

    for (
      const manifestPath
      of manifestPaths
    ) {
      let manifest:
        RecoveryPointDeletionManifest;

      try {
        const contents =
          await readFile(
            manifestPath,
            "utf8"
          );

        const parsed: unknown =
          JSON.parse(contents);

        if (!isDeletionManifest(parsed)) {
          continue;
        }

        manifest = parsed;
      } catch {
        continue;
      }

      if (
        manifest.auctionSession.id !==
          input.auctionSessionId ||
        manifest.database.fileName !==
          input.fileName
      ) {
        continue;
      }

      const expectedManifestName =
        `${input.fileName.slice(
          0,
          -".sqlite".length
        )}.json`;

      if (
        path.basename(manifestPath) !==
        expectedManifestName
      ) {
        continue;
      }

      const directory =
        path.dirname(manifestPath);

      const sqlitePath =
        path.join(
          directory,
          input.fileName
        );

      /*
       * The manifest is removed last.
       *
       * If SQLite deletion fails, the manifest
       * remains available and still describes
       * the recovery point.
       */
      await rm(sqlitePath, {
        force: true
      });

      await rm(manifestPath);

      return {
        fileName: input.fileName
      };
    }

    throw new RecoveryPointNotFoundError();
  }
}
